services:
  backend:
    build:
      context: ./ai-assistant-backend
      dockerfile: Dockerfile
    container_name: ai-assistant-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_KEY=${API_KEY}
      - PORT=3000
    networks:
      - app-network

  frontend:
    build:
      context: ./ai-assistant-frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000/api/v1/chat
    container_name: ai-assistant-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
